export const siteConfig = {
  name: "Edmond Yeo | Developer Portfolio",
  authorName: "Edmond Yeo",
  username: "namanbarkiya",
  description:
    "Edmond Yeo's portfolio - A modern, responsive Dry Needling portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://x.com/namanbarkiya",
    github: "https://github.com/namanbarkiya",
  },
  ogImage: "https://nbarkiya.xyz/profile-img.jpg",
  iconIco:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico",
  logoIcon:
    "https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png",
  keywords: [
    "Edmond Yeo",
    "Physiotherapist",
    "Web Developer Portfolio",
    "Dry Needling portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Dry Needling template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Physiotherapist portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Dry Needling 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
